// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen6;
lv_obj_t * ui_Image7;

// event funtions

// build funtions

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image7, &ui_img_999427845);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 283
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_x(ui_Image7, 0);
    lv_obj_set_y(ui_Image7, -9);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_Screen6_screen_destroy(void)
{
    if(ui_Screen6) lv_obj_del(ui_Screen6);

    // NULL screen variables
    ui_Screen6 = NULL;
    ui_Image7 = NULL;

}
